const TEAMS = [
  "GPDES",
  "SPUFF",
  "PSICO UFRJ",
  "PSICO PUC",
  "GEMEL",
  "AECS",
  "RI UFF",
  "HOTUR UFF",
  "RI UFRJ",
];

// Arquivo de logo em img/teams/<key>.png — adicione o arquivo e aparece automaticamente
const TEAM_COLORS = {
  GPDES: "#c0541a",
  SPUFF: "#1a6fc0",
  "PSICO UFRJ": "#1a6fc0",
  "PSICO PUC": "#1a8c3a",
  GEMEL: "#8c1a1a",
  AECS: "#7a1a8c",
  "RI UFF": "#c0a01a",
  "HOTUR UFF": "#1a8c8c",
  "RI UFRJ": "#1a6fc0",
};

const POINTS_BY_PLACEMENT = {
  1: 16,
  2: 13,
  3: 10,
  4: 9,
  5: 6,
  6: 5,
  7: 4,
  8: 3,
  9: 2,
};

const SPORT_ICONS = {
  "Cabo Guerra Masc": "💪",
  "Cabo Guerra Fem": "💪",
  "Tenis Mesa Masc": "🏓",
  "Tenis Mesa Fem": "🏓",
  Fut7: "⚽",
  "Basquete Masc": "🏀",
  "Basquete Fem": "🏀",
  "Volei Masc": "🏐",
  "Volei Fem": "🏐",
  "Handebol Masc": "🤾",
  "Handebol Fem": "🤾",
  "Futsal Masc": "🥅",
  "Futsal Fem": "🥅",
};

// Chaveamento de cada esporte: B4 e B5 jogam na 1ª rodada;
// D8..D20 entram direto na rodada 2 (byes)
const BRACKETS = {
  "Cabo Guerra Masc": {
    B4: "PSICO PUC",
    B5: "PSICO UFRJ",
    D8: "RI UFF",
    D10: "RI UFRJ",
    D12: "AECS",
    D14: "HOTUR UFF",
    D16: "GEMEL",
    D18: "SPUFF",
    D20: "GPDES",
  },
  "Cabo Guerra Fem": {
    B4: "AECS",
    B5: "GEMEL",
    D8: "PSICO UFRJ",
    D10: "SPUFF",
    D12: "RI UFRJ",
    D14: "PSICO PUC",
    D16: "RI UFF",
    D18: "GPDES",
    D20: "HOTUR UFF",
  },
  "Tenis Mesa Masc": {
    B4: "SPUFF",
    B5: "HOTUR UFF",
    D8: "GEMEL",
    D10: "RI UFF",
    D12: "PSICO PUC",
    D14: "GPDES",
    D16: "AECS",
    D18: "PSICO UFRJ",
    D20: "RI UFRJ",
  },
  "Tenis Mesa Fem": {
    B4: "GPDES",
    B5: "RI UFF",
    D8: "RI UFRJ",
    D10: "PSICO PUC",
    D12: "SPUFF",
    D14: "AECS",
    D16: "GEMEL",
    D18: "PSICO UFRJ",
    D20: "HOTUR UFF",
  },
  Fut7: {
    B4: "SPUFF",
    B5: "RI UFRJ",
    D8: "AECS",
    D10: "PSICO UFRJ",
    D12: "PSICO PUC",
    D14: "RI UFF",
    D16: "HOTUR UFF",
    D18: "GPDES",
    D20: "GEMEL",
  },
  "Basquete Masc": {
    B4: "PSICO PUC",
    B5: "RI UFRJ",
    D8: "GPDES",
    D10: "PSICO UFRJ",
    D12: "AECS",
    D14: "RI UFF",
    D16: "GEMEL",
    D18: "SPUFF",
    D20: "HOTUR UFF",
  },
  "Basquete Fem": {
    B4: "RI UFRJ",
    B5: "SPUFF",
    D8: "HOTUR UFF",
    D10: "GPDES",
    D12: "AECS",
    D14: "PSICO PUC",
    D16: "RI UFF",
    D18: "PSICO UFRJ",
    D20: "GEMEL",
  },
  "Volei Masc": {
    B4: "GEMEL",
    B5: "SPUFF",
    D8: "RI UFRJ",
    D10: "HOTUR UFF",
    D12: "RI UFF",
    D14: "GPDES",
    D16: "PSICO UFRJ",
    D18: "PSICO PUC",
    D20: "AECS",
  },
  "Volei Fem": {
    B4: "AECS",
    B5: "GEMEL",
    D8: "RI UFF",
    D10: "PSICO UFRJ",
    D12: "HOTUR UFF",
    D14: "RI UFRJ",
    D16: "SPUFF",
    D18: "PSICO PUC",
    D20: "GPDES",
  },
  "Handebol Masc": {
    B4: "AECS",
    B5: "PSICO UFRJ",
    D8: "GPDES",
    D10: "RI UFF",
    D12: "GEMEL",
    D14: "PSICO PUC",
    D16: "RI UFRJ",
    D18: "SPUFF",
    D20: "HOTUR UFF",
  },
  "Handebol Fem": {
    B4: "RI UFF",
    B5: "GPDES",
    D8: "GEMEL",
    D10: "SPUFF",
    D12: "RI UFRJ",
    D14: "PSICO PUC",
    D16: "HOTUR UFF",
    D18: "PSICO UFRJ",
    D20: "AECS",
  },
  "Futsal Masc": {
    B4: "HOTUR UFF",
    B5: "GPDES",
    D8: "AECS",
    D10: "GEMEL",
    D12: "RI UFF",
    D14: "PSICO UFRJ",
    D16: "SPUFF",
    D18: "PSICO PUC",
    D20: "RI UFRJ",
  },
  "Futsal Fem": {
    B4: "HOTUR UFF",
    B5: "RI UFF",
    D8: "PSICO PUC",
    D10: "PSICO UFRJ",
    D12: "GPDES",
    D14: "AECS",
    D16: "RI UFRJ",
    D18: "SPUFF",
    D20: "GEMEL",
  },
};

const SPORT_NAMES = Object.keys(BRACKETS);
